name: Run steps on Docker and Runner

on:
  workflow_dispatch:

jobs:
  hybrid_job:
    runs-on: ubuntu-latest

    steps:
      - name: run command on ubuntu Runner vm
        run: echo "This runs on ubuntu VM"

      - name: run command on docker container
        uses: docker://alpine:3.14
        with:
          entrypoint: /bin/sh
          args: |
                -c "echo 'This runs inside Alpine container';
                ls -la;
                whoami;
                "

      - name: run back-to ubuntu Runner vm

        run: echo "This back-to ubuntu VM"


  dockerized_job:
    runs-on: ubuntu-latest 
    container: node:20

    steps:
      - name: node vesion
        run: node --version
      
      - name: print vesion
        run: echo "whole jobs run on node container"


