name: matrix strategy

on: 
  workflow_dispatch:

jobs:
  Test_Os_Node:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node_version: [14.x, 15.x, 16.x]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-node@v6.0.0
        with:
          node-version: ${{ matrix.node_version }}
        
        
      
