name: Test Private Docker Image

on:
  workflow_dispatch: 

jobs:
  test_private_docker_image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 2: Pull your private Docker image
      - name: Pull private Docker image
        run: docker pull youssefabdulaty/mynode:latest

      # Step 3: Run the container and test
      - name: Run Docker container
        run: |
          docker run --rm youssefabdulaty/mynode:latest

