name: Test Private Docker Image

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter name to greet"
        required: true
        default: Youssef
        type: string

jobs:
  test_private_docker_image:
    runs-on: ubuntu-latest
    container:
      image: youssefabdulaty/mynode:latest
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Test Node.js
        run: node -e "console.log('Hello from Docker container!')"

      - name: Test script.js 
        run: node script.js ${{ github.event.inputs.name }}
