name: Test Private Docker Image

on:
  workflow_dispatch:

jobs:
  test_private_docker_image:
    runs-on: ubuntu-latest
    container:
      image: youssefabdulaty/mynode:latest
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Test app.js in youssefabdulaty container
        run: node app.js
