name: Publish when Tag Version

on:
  push:
    tags:
      - "v*"   # يشغّل الـ workflow لأي Tag يبدأ بـ v

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Only run if this is tag starting with v
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "This is version tag: ${{ github.ref }}"

      - name: Normal run
        run: echo "This runs always"
